[run]
name = ''
random_seed = 64

[datafiles]
source = "fivemin_data.csv"
drop_cols = ["wmo_hr_sun_dur"]
rename_dict = {}
model_path = "gpr_model.joblib"
col_desc = 'variable_description.json'

[train_test]
predictors = ["minutes", "GHE"]  # minutes, hours, GHE, sol_alt, sol_az, cld_ttl_amt_id
target = ["GHI"]
train_days = [1, 1]
train_month = 3
train_year = 2015
training_ratio = 0.7
scaling_mode = "Standard"  # Standard, MinMax

[gpr]
alpha = 1.0
max_iters = 1e6
n_restarts_optimizer = 20

[output]
run_dir = ''
plot_dir = ''
calc_dependent_vars = false
dependent_vars = []
benchmarks = ['linear']
