[run]
name = "Case_4_cumulative"

[datafiles]
source = "hourly_data.csv"

[train_test]
train_days = [ 1, 31,]
train_month = 12
train_year = 2015
training_ratio = 0.7
test_days = [ 1, 31,]
test_month = 12
test_year = 2016

[output]
benchmarks = [ "linear", "polynomial2", "random_forest",]