[datafiles]
source = "fivemin_data.csv"
drop_cols = ["wmo_hr_sun_dur"]
rename_dict = {"Unnamed: 0"= "datetime", "sol altitude"= "sol_alt", "sol azimuth"= "sol_az"}
model_path = "gpr_model.joblib"

[filter]
days = [1, 1]
month = 3
year = 2015

[train_test]
predictors = ["minutes", "GHE"]
target = ["GHI"]
training_ratio = 0.7
scaling_mode = "standard"

[gpr]
alpha = 1.0
n_restarts_optimizer = 20

