[run]
name = "Test"

[datafiles]
source = "hourly_data.csv"

[train_test]
predictors = ["hours", "GHE"]
#predictors = ["hours", "GHE", "sol_alt", "sol_az", "cld_ttl_amt_id"]
#target = ["GHI", "DHI", 'DNI']

[filter]
days = [1, 31]
month = 6
year = 2016
